### PR TITLE
Add CI for linux and macos

### PR DESCRIPTION
**Pull request by junjihashimoto**
Hi, 
This pr improves https://github.com/tweag/jupyterWith/issues/74 and https://github.com/tweag/jupyterWith/issues/53 .

### CODE REVIEW

**Comment by MMesch** [comment]
Nice thanks @junjihashimoto ! @guaraqe, you did most of the CI related setup, can you check this one?

**Comment by guaraqe** [comment]
This looks nice! I don't know GitHub actions very well, so I will do some research so I can test it properly, and I will come back to this PR.

Thanks!

**Comment by guaraqe** [comment]
Hello, sorry for the large delay. For some time we didn't have GitHub actions activated in our account, but since now they are open for all, we will be able to use that!

I will do some tests and come back soon.

**Comment by junjihashimoto** [comment]
This PR just does CI.
If you want to do CD uploading nix cache to cachix, this action is helpful.
https://github.com/cachix/cachix-action

**Comment by guaraqe** [comment]
@junjihashimoto Once more, thanks for this, I am merging so I stop spending your actions!

**Comment by junjihashimoto** [comment]
Thx!

**Pull request merged**
