### PR TITLE
Add Julia kernel

### PR DESCRIPTION
**Pull request by GTrunSec**
The PR requirement involved in https://github.com/tweag/jupyterWith/issues/161

### CODE REVIEW

**Comment by GTrunSec** [comment]
waiting for rebasing my latest rev.https://github.com/tweag/jupyterWith/pull/179

**Comment by GTrunSec** [comment]
DONE for testing:

image

**Comment by GTrunSec** [comment]
@guaraqe please review.

**Review by guaraqe — APPROVED** [review]
Thanks! I am happy this works in a simpler way now.

Sometime we will have to update the list of kernels in the README.

**Pull request merged**
