### PR TITLE
kernels/ihaskell: add kernel.js for syntax highlighting in classic notebook interface

### PR DESCRIPTION
**Pull request by vaibhavsagar**

### CODE REVIEW

**Comment by guaraqe** [comment]
This is very useful, thank you!

**Comment by vaibhavsagar** [comment]
My pleasure! IHaskell also now provides a [prebuilt extension](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#prebuilt-extensions) for syntax highlighting in JupyterLab [here](https://github.com/gibiansky/IHaskell/tree/cf29b2c52d35df6aeb130794b447855a9683e947/jupyterlab-ihaskell/labextension), would it be helpful for me to open a PR for that as well?

**Comment by guaraqe** [comment]
> My pleasure! IHaskell also now provides a [prebuilt extension](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#prebuilt-extensions) for syntax highlighting in JupyterLab [here](https://github.com/gibiansky/IHaskell/tree/cf29b2c52d35df6aeb130794b447855a9683e947/jupyterlab-ihaskell/labextension), would it be helpful for me to open a PR for that as well?

We currently have lots of diffuse advices on the main README of how to use the extension (impure building, code mirror, local version, etc...), do you think we can do something out-of-the box? If we can, that would be very useful!

**Comment by vaibhavsagar** [comment]
Yes, this is automatic, you can see how I implemented support [here](https://github.com/gibiansky/IHaskell/blob/cf29b2c52d35df6aeb130794b447855a9683e947/release.nix#L85-L94). I'll open a PR later today.

**Pull request merged**
