### PR TITLE
gophernotes: use newer version packaged in nixpkgs

### PR DESCRIPTION
**Pull request by oxzi**
The more recent gophernotes version (0.7.0 → 0.7.1) is used from the nixpkgs. Therefore the nixpkgs needed to be updated.

### CODE REVIEW

**Comment by guaraqe** [comment]
The MacOS test was not passing, I relaunched it.

**Comment by oxzi** [comment]
I'm not quite sure, but it seems like bumping the nixpkgs breaks some tests on macOS.

**Comment by guaraqe** [comment]
I have the impression it's some other package that is broken for Mac in Nixpkgs at this moment. Updating Nixpkgs here is always delicate, so I prefer to not do it right now.

But if you are willing, I would accept an update of gophernotes to the latest version.

**Comment by oxzi** [comment]
Okay, I have modified the Pull Request to just bump `gophernotes` to its latest release.

**Review by guaraqe — APPROVED** [review]

**Comment by guaraqe** [comment]
Thanks!

**Pull request merged**
