### PR TITLE
Add julia2nix to julia kernel

### PR DESCRIPTION
**Pull request by GTrunSec**
The julia2nix can bring a better experience to Julia under nix.

### CODE REVIEW

**Comment by GTrunSec** [comment]
@djacu @garbas ready to review.

**Comment by djacu** [comment]
Thanks for the PR @GTrunSec! I'll take a look and talk with @garbas about it.
One question: What was the need to pin the rust-overlay?

**Comment by GTrunSec** [comment]
> https://github.com/tweag/jupyterWith/pull/254/commits/dbd0d2976c765eb37911542cf03387a823e115b3#diff-0cf43306384affa3eb860259e704ee405ca9b810494552cb4ca31ad008f0c527L18

If you fetchtabll from `the master.tar.gz,` the sha256 will not be immutable.

**Comment by GTrunSec** [comment]
Also, you can import the rust-overlay from `inputs` instead.

**Comment by GTrunSec** [comment]
I saw your issue from julia2nix. if you want to generate the depot you can try this [example](https://github.com/JuliaCN/Julia2Nix.jl/blob/main/templates/dev/flake.nix#L40) in your desire.

**Comment by GTrunSec** [comment]
I'm currently the maintainer of [julia2nix](https://github.com/JuliaCN/Julia2Nix.jl), and I recommend that you include me as the maintainer of the julia kernel. Due to the complexity of Julia in different environments with nix, we should provide an interface for various examples.

**Comment by djacu** [comment]
Sure thing! I haven't had a chance to talk with @garbas yet, but I'll bring that up as well as your PRs. Sorry for the delay; I'm still getting a handle on updating and maintaining this repo.

**Comment by djacu** [comment]
Hey @GTrunSec 
I need to get the next version of jupyterWith working by August. I appreciate the work you have put in but I do not have time to review everything properly right now. We can come back to julia and maintainership after the next version is in and in a stable state.

**Comment by garbas** [comment]
@GTrunSec I took the time to review the PR. `julia2nix` looks a useful project, but I'm concerned to add it due to being an `std` project. I understand you offered your help to maintain the julia kernel, but that would make it impossible for anybody else to help out (which is not bad).

It is possible to extend any existing kernel to use any other `*2nix` tool (we're working on the documentation as we speak) or even write your own kernel in a different flake (also writing this documentation). I'll ping you when documentation is done so you can use `julia2nix` and write julia kernel in another flake.

I would just hope `julia2nix` would be a more simple nix flake project which a regular nix engineer could understand.

**Comment by GTrunSec** [comment]
I have modularized julia2nix as much as possible, and users can add corresponding modules according to their conditions. It's just that we need a clear example to explain the different situations and APIs interfaces.

**Pull request closed without merging**
