### PR TITLE
kernels: add bash kernel

### PR DESCRIPTION
**Pull request by rissson**
Should work as expected

### CODE REVIEW

**Comment by guaraqe** [comment]
Hi, can you rebase on master? I just updated the MacOS action, which was failing, maybe that will solve the problem.

**Comment by guaraqe** [comment]
Tests are passing, thanks!

**Comment by guaraqe** [comment]
You can add an example in the `examples` folder if you think that is helpful.

**Comment by l0b0** [comment]
Thank you very much!

Is this missing an icon and example in the readme file?

**Pull request merged**
