### PR TITLE
feature: add julia kernel support

### PR DESCRIPTION
**Pull request by GTrunSec**
Regarding comments in https://github.com/tweag/jupyterWith/pull/89#issuecomment-630061015

### CODE REVIEW

**Comment by GTrunSec** [comment]
- feature: Julia CUDA support.
Based on https://github.com/hardenedlinux/NSM-data-analysis/blob/master/pkgs/julia.nix

**Comment by GTrunSec** [comment]
fix julia multi-threads
```
./result/bin/julia_wrapped
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> Threads.nthreads()
8

julia> 
```

**Comment by GTrunSec** [comment]
https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility__table-toolkit-driver
- test failed with nvidiaBeta on NixOS (CUDA_10_2)
```
nvidia-smi                                                                                                                             
Mon May 18 20:24:24 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   41C    P8     6W / 180W |    382MiB /  8116MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                                
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1497      G   ...lvnf490s0nkpyf-xorg-server-1.20.8/bin/X   366MiB |
|    0     22639      G   /run/current-system/sw/bin/kitty              12MiB |
+-----------------------------------------------------------------------------+
```

**Comment by GTrunSec** [comment]
Not in the merge PR list. Just a CUDA test for Julia ( FIxed mismatch between  Nvidia and cuda.)

```
  [d6f4376e] Markdown  [`@stdlib/Markdown`]                                                                                              
  [de0858da] Printf  [`@stdlib/Printf`]                                                                                                  
  [9a3f8284] Random  [`@stdlib/Random`]                                                                                                  
  [9e88b42a] Serialization  [`@stdlib/Serialization`]                                                                                    
  [6462fe0b] Sockets  [`@stdlib/Sockets`]                                                                                                
  [8dfed614] Test  [`@stdlib/Test`]                                                                                                      
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]                                                                                                
[ Info: Testing using device GeForce GTX 1070 Ti (compute capability 6.1.0, 7.479 GiB available memory) on CUDA driver 10.2.0            
check = [0 0 0; 0 0 0; 0 0 0]                                                                                                            
check = [0 1 0 0; 0 2 0 0; 0 3 0 0; 0 4 0 0]                                                                                             
                                                                                                                                         
[0 5 0 0; 0 6 0 0; 0 7 0 0; 0 8 0 0]                                                                                                     
                                                                                                                                         
[0 9 0 0; 0 10 0 0; 0 11 0 0; 0 12 0 0]                                                                                                  
                                                                                                                                         
[0 13 0 0; 0 14 0 0; 0 15 0 0; 0 16 0 0]                                                                                                 
┌ Warning: Calling CUDAdrv.@profile only informs an external profiler to start.                                                          
│ The user is responsible for launching Julia under a CUDA profiler like `nvprof`.                                                       
│                                                                                                                                        
│ For improved usability, launch Julia under the Nsight Systems profiler:                                                                
│ $ nsys launch -t cuda,cublas,cudnn,nvtx julia                                                                                          
└ @ CUDAdrv.Profile ~/data/master-jupyter/.julia_pkgs/packages/CUDAdrv/Uc14X/src/profile.
```

**Comment by guaraqe** [comment]
I don't understand the comments in this PR, could you explain what is happening?

I see that Julia is not supported in Nixpkgs, and that you have a way to go around it. Does this uses Nix to go around or not?  I would be very glad if you could explain:

- What is the method to go around the lack of Julia support in Nixpkgs.
- Which features you aimed to support. I see you tried to add CUDA support. Shouldn't this kind of thing go in Nixpkgs instead?
- How can I test this.

Also, don't use your own Nixpkgs snapshot, always import ours using `callPackage` or something else. It is hard enough maintaining our set of overrides, and upgrades are always painful.

**Comment by GTrunSec** [comment]
> What is the method to go around the lack of Julia support in Nixpkgs.
- Actually, we don't need the Julia packages' manager in Nixpkgs.  Julia mainly programs enough for us to use it. https://github.com/NixOS/nixpkgs/pull/79174#issuecomment-590585298 (this is why I need my own snapshot.  
  -  I'm not sure which snapshot of nixpkgs can be passed (also, you can check the hydra CI .https://hydra.nixos.org/job/nixpkgs/trunk/julia_13.x86_64-linux/all  No one information about Julia passing rev applied for us.
> How can I test this.

if you are for the first time running Julia kernel. (please run command `Install_Ijulia` to  initializing JULIA_PKGDIR (  related to  `directory = "./.julia_pkgs";`)

> Which features you aimed to support. I see you tried to add CUDA support. Shouldn't this kind of thing go in Nixpkgs instead?

- Similarly, the CUDA feature able to adapt to everyone.  
  - first of all, check https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility__table-toolkit-driver and `nvidia-smi`. What are your versions between `CUDA` and `Nvidia-video-version.` For me, I installed `linuxPackages.nvidia_x11_beta`  
  - you should replace the cudapkgs to snapshot of nixpkgs which in your current `Nvidia-video-version`. such as linuxPackages.nvidia_x11_legacy390, linuxPackages.nvidia_x11_legacy340 or something else.
Also, run the command `./result/bin/Install_Julia_CUDA` to installs the CUDA environment and fix the hard link problem easily.

**Comment by GTrunSec** [comment]
About the CI problem. The Julia compiling for 1h may not passing in your rev of nixpkgs, and some complex dependencies hard to test it.
So, I wrote  a `release.nix` for Jupyterwith and my `own-Jupyterwith-environment`
image

**Comment by GTrunSec** [comment]
Optional Nixpkgs

```
  cudapkgs =  import (builtins.fetchTarball "https://github.com/GTrunSec/nixpkgs/tarball/927fcf37933ddd24a0e16c6a45b9c0a687a40607"){};

  iJulia = jupyter.kernels.iJuliaWith {
    name =  "Julia-test";
    directory = "./.julia_pkgs";
    nixpkgs =  import (builtins.fetchTarball "https://github.com/GTrunSec/nixpkgs/tarball/39247f8d04c04b3ee629a1f85aeedd582bf41cac"){};
    cudapkgs =  import (builtins.fetchTarball "https://github.com/GTrunSec/nixpkgs/tarball/927fcf37933ddd24a0e16c6a45b9c0a687a40607"){};
    NUM_THREADS = 8;
    cuda = true;
    cudaVersion = cudapkgs.cudatoolkit_10_2;
    extraPackages = p: with p;[   # GZip.jl # Required by DataFrames.jl
      gzip
      zlib
      cudapkgs.cudatoolkit_10_2
    ];
  };
```

**Comment by guaraqe** [comment]
To make sure I understand:

- You install Julia packages using it's own package manager. Then you take your manually generated folder, and feed it to the Nix expression. Isn't it better to just generate a kernel which calls the `julia` executable that is in the environment, without wrapping, and adding Julia to the packages that are in the shell? In that way the setup is entirely up to the user, and there are less steps and configuration options.

- I updated Nixpkgs in master. Does it help you?

**Pull request closed without merging**
