### PR TITLE
Is it necessary to set python's argument of ignore collisions  to true by default?

### PR DESCRIPTION
**Pull request by GTrunSec**
In my opinion and python experience.  this argument should be here.
What do you think?

### CODE REVIEW

**Comment by guaraqe** [comment]
Thanks for your contribution. What is the goal of this PR exactly? I don't really know what this flag does. Does it solve some problem you had?

**Comment by GTrunSec** [comment]
this flag from here https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#pythonbuildenv-function
you know, the python packages of Nixpkgs always using replace setup.py's dep version to suitable versions which are in current python version of nixpkgs(even patch it to override). 

Actually,  some python package does not support highly version or a full feature. So the package version should be a special version which in `setup.py` rather than a version of nixpkgs.
that's why  `ignoreCollisions = true` appeared in python `buildEnv` frequently.

**Comment by guaraqe** [comment]
Ok, so if I understand well, this flag is useful for you. If that is so, why not add it instead to the arguments of the kernel? Something like:
```
{
...
, ignoreCollisions ? false
...
}
<code>
```

And then the set attribute to the value in this function? I think the default value should be false, so the current behavior does not change.

If you think this is a good idea, add the new flag to the kernel README, that is in the safe folder as the file you just changed.

**Comment by GTrunSec** [comment]
> , ignoreCollisions ? false

yes,  I'm pretty sure this good idea to control the value of ignore collisions which you needed or not.  thanks for reminding me.

**Pull request merged**
