### PR TITLE
add flake support

### PR DESCRIPTION
**Pull request by GTrunSec**
- CI
 ```
nix develop ./example/flake --command echo OK
```

### CODE REVIEW

**Comment by guaraqe** [comment]
Thanks for that, can you rebase it on the current master? Maybe that will fix the tests.

**Comment by GTrunSec** [comment]
Setting the cachix of jupyterwtih to nixconf.extra in flakes.nix

**Comment by GTrunSec** [comment]
@guaraqe Any question about flake?

**Review by guaraqe — APPROVED** [review]
This is nice, thank you!

**Pull request merged**
