### PR TITLE
Disable default python kernel

### PR DESCRIPTION
**Pull request by Etjean**
This disables the default python kernel in `jupyter-lab`, `jupyter-notebook`, and `jupyter-nbclassic`.

### CODE REVIEW

**Comment by guaraqe** [comment]
The MacOS tests are not passing, due to the tests of some component of Jupyter not working.

**Comment by guaraqe** [comment]
The setup upterm task has been running for 3 hours already.

**Comment by Etjean** [comment]
The flake checks currently fail with
```
error: input 'jupyterWith/ihaskell/hls/pre-commit-hooks/flake-utils' follows a non-existent input 'hls/flake-utils'
```

According to [this thread](https://github.com/NixOS/nix/issues/3602), it happens when one of the flake input uses the "follows" attribute. Among the chain of inputs, only `ihaskell` used to use this "follows" directive in its flake inputs, but [this is now solved](https://github.com/haskell/haskell-language-server/pull/2218).

When running the flake checks locally, everything runs fine. I suspect cachix uses some cached version of jupyterWith, or iHaskell, that precedes the fix introduced in iHaskell that is linked above. I'm not familiar with cachix, so I'm not sure how to fix that at the moment.

**Comment by GTrunSec** [comment]
Just run `nix flake lock --update-input ihaskell`  to fix the flake issue.

**Comment by Etjean** [comment]
@GTrunSec, Thanks for the suggestion. I gave it a try but that still doesn't pass. Even without updating the lockfile, iHaskell is recent enough, and running `nix flake lock --override-input jupyterWith ../..` locally works fine too.

**Comment by GTrunSec** [comment]
How about `cd example/flake` then `nix flake update`? if it does not work again, I will add the follows for the ihaskell input.

**Comment by Etjean** [comment]
That worked, thanks a lot @GTrunSec.
For some reason, the flake checks failed with nix 2.6, while they passed with nix 2.5. Updating the lockfile in `example/flake` made them pass with nix 2.6 as well.

**Comment by guaraqe** [comment]
That's great, thanks!

**Pull request merged**
