### PR TITLE
Feature/add opam nix

### PR DESCRIPTION
**Pull request by djacu**
Switch to using [opam-nix](https://github.com/tweag/opam-nix) to build the OCaml kernel. Thanks @balsoft for the help.

@fusetim would you mind testing this and making sure it works for you?

Currently in draft until I get verify a few things.

### CODE REVIEW

**Comment by fusetim** [comment]
Amazing work, I'll add a reminder to try this next Thursday. 👍

**Comment by djacu** [comment]
Awesome! Thanks for taking the time. I'm really curious if you are able to provide additional ocaml packages via `extraRuntimePackages`. I imagine it might not work properly and that we will have to set some additional path manually like we did with `CAML_LD_LIBRARY_PATH`.

**Comment by fusetim** [comment]
Unfortunately, I guess something is wrong somewhere. I'm unable to build jupyterWith with the default OCaml environment. Something linked to the import of `opam-nix` is broken. I'm not able to find the issue, since I'm still a real begginer with Flakes (I recently discovered `nix run --recreate-lock`).

Here are the logs: 
> $ nix run --recreate-lock-file    warning: Using saved setting for 'extra-substituters = https://tweag-jupyter.cachix.org' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = tweag-jupyter.cachix.org-1:UtNH4Zs6hVUFpFBTLaA4ejYavPo5EFFqgd7G7FxGW9g=' from ~/.local/share/nix/trusted-settings.json.
warning: ignoring untrusted substituter 'https://tweag-jupyter.cachix.org'
warning: updating lock file '/home/fusetim/Documents/MPI/Physique/DM3_Cyclotron/flake.lock':
• Updated input 'jupyterWith':
    'git+file:///home/fusetim/Documents/Dev/jupyterWith' (2022-11-15)
  → 'git+file:///home/fusetim/Documents/Dev/jupyterWith?ref=refs%2fheads%2ffeature%2fadd-opam-nix&rev=372926399568610889236cdb2e2200669785399b' (2022-11-15)
• Updated input 'jupyterWith/flake-compat':
    'github:edolstra/flake-compat/009399224d5e398d03b22badca40a37ac85412a1' (2022-11-17)
  → 'github:edolstra/flake-compat/b4a34015c698c7793d592d66adbab377907a2be8' (2022-04-19)
• Updated input 'jupyterWith/nixpkgs':
    'github:nixos/nixpkgs/b457130e8a21608675ddf12c7d85227b22a27112' (2022-11-16)
  → 'github:nixos/nixpkgs/3bacde6273b09a21a8ccfba15586fb165078fb62' (2022-11-05)
• Updated input 'jupyterWith/nixpkgs-stable':
    'github:nixos/nixpkgs/814f8f3363cecee7cce314286846e4da5e92d689' (2022-11-15)
  → 'github:nixos/nixpkgs/f09ad462c5a121d0239fde645aacb2221553a217' (2022-11-05)
• Updated input 'jupyterWith/poetry2nix':
    'github:nix-community/poetry2nix/3cc82ca6ccca2a06dbb05cb0b74efd5d50e60d48' (2022-11-14)
  → 'github:nix-community/poetry2nix/6c2f092d74360102dcc4eb16cc93d562e5d35dcc' (2022-11-07)
• Updated input 'jupyterWith/pre-commit-hooks':
    'github:cachix/pre-commit-hooks.nix/ebcbfe09d2bd6d15f68de3a0ebb1e4dcb5cd324b' (2022-11-09)
  → 'github:cachix/pre-commit-hooks.nix/06f48d63d473516ce5b8abe70d15be96a0147fcd' (2022-11-06)
• Updated input 'jupyterWith/rust-overlay':
    'github:oxalica/rust-overlay/c91265a3f0d28b3b1ad60a47c4764a45b111ed4b' (2022-11-17)
  → 'github:oxalica/rust-overlay/528499f67169671e931cf1ba63601803e58abd2a' (2022-11-07)
error: attribute 'opam-nix' missing
>
>       at /nix/store/0qiw5y611p87nm60jcblrv6q26gb7qar-source/kernels/available/ocaml/default.nix:21:5:
>
>           20|   in
>           21|     pkgs.opam-nix.buildDuneProject
>             |     ^
>           22|     {
>(use '--show-trace' to show detailed location information)

I suspect the reason is hidden there: https://github.com/tweag/jupyterWith/pull/356/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R173-R178
Either the overlay is not applied or it should happen there.

**Comment by djacu** [comment]
Yup I just ran into this issues yesterday on #358. When building the environment within the jupyterWith repo everything works because `pkgs` has the locally applied overlays. But when using the template, it is using the user's `pkgs` which doesn't have the overlay.

It does work for the haskell kernel but I need to speak with @garbas if we want to continue using the overlays or implement this in a different way.

Thanks for taking the time to test it out. I'll let you know when things are in a better state. And next time I'll remember to test the template myself. :sweat_smile:

**Review by garbas — APPROVED** [review]

**Pull request merged**
