### PR TITLE
Add rust kernel

### PR DESCRIPTION
**Pull request by kristoff3r**
Tested using the notebook from [this post](https://shahinrostami.com/posts/programming/rust-notebooks/chord-diagrams/) and another post from the same excellent blog.

### CODE REVIEW

**Comment by guaraqe** [comment]
Thanks for this! Can you add an example in the examples folder, under `examples/Rust/simple`, for example? A simple notebook, which runs any command that depends only on the base library should be good.

This will make it easier to test the PR.

**Comment by kristoff3r** [comment]
I found a mistake which I fixed, I added a prettier logo from evcxr, and I added a simple example. Let me know if you want other changes.

**Comment by guaraqe** [comment]
So, I launched the `shell.nix` in the examples folder, and launched `jupyter lab`. I open the notebook, and try to re-evaluate the first cell, I get the following error:

```
[I 14:30:58.452 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
Error: Message("No such file or directory (os error 2)")
```

**Comment by kristoff3r** [comment]
Ah, that is because it depends on another pull request I have for evcxr in nixpkgs: https://github.com/NixOS/nixpkgs/pull/91895

I reworked the kernel a bit to make it work out of the box even without that PR landing, and added a packages attribute to make it easier to add extra dependencies. Also, this time I tested it in a pure shell, so hopefully it works now :D

Thanks for testing it!

**Comment by guaraqe** [comment]
Nice, it works well, thanks! Can you:

- Change its name to `rustWith`, just so it follows the pattern from other kernels.
- Add it to the `tests/default.nix` file, so it is tested by the CI.

After this, I will merge the PR.

**Pull request merged**
