### PR TITLE
Fix flake

### PR DESCRIPTION
**Pull request by teto**
I've tried using the flake in my project referencing jupyterWith.overlay but it failed with `error: attribute 'jupyter_contrib_core' missing`.
I fixed that and made it pass `nix flake check`. There is a breaking change though.

### CODE REVIEW

**Comment by guaraqe** [comment]
Thanks for the PR, I'm not very experienced with Flakes yet, this is useful. I launched tests.

I have the impression that the changes to the two overlay files are superficial, can you keep the original?

@GTrunSec Since you wrote the Flake, can you take a look at the PR?

**Comment by teto** [comment]
> I have the impression that the changes to the two overlay files are superficial, can you keep the original?

`nix flake check` requires the parameters to be called `prev` and `final` so I can't keep the original. 

I will look into the CI failure. One cool tool though is https://github.com/edolstra/flake-compat/ that allows to run a legacy nix-shell while using the flake as a source of truth (mentioning this since I see the failing job comes from a devshell.nix).

**Comment by teto** [comment]
I fixed the example flake, should be good now.

**Comment by guaraqe** [comment]
This is working now, thank you!

**Comment by rokroskar** [comment]
I'm running into this issue (an error about `jupyter_contrib_core` not being found) when trying to build a docker image - I'm trying to build this:

```
let
  pkgs = import <nixpkgs> { system = "x86_64-linux";};
  jupyter = import (builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
    rev = "6024eb9329c5f47102adc26f541712121bba62d4";
  }) {inherit pkgs;};

  jupyterEnvironment = jupyter.jupyterlabWith {};
in
    pkgs.dockerTools.buildLayeredImage {
      name = "jupyter";
      tag = "latest";
      created = "now";
      contents = [ jupyterEnvironment ];
      config = {
          Env = [
              "LOCALE_ARCHIVE=${pkgs.glibcLocales}/lib/locale/locale-archive"
              "LANG=en_US.UTF-8"
              "LANGUAGE=en_US:en"
              "LC_ALL=en_US.UTF-8"
          ];
          CMD = [ "/bin/jupyter-lab" "--ip=0.0.0.0" "--no-browser" "--allow-root" ];
          WorkingDir = "/data";
          ExposedPorts = {
              "8888" = {};
          };
          Volumes = {
              "/data" = {};
          };
      };
  }
```


I'm not sure if the issue is in the way I import `pkgs` or whether there is an issue with `jupyter_contrib_core`?

**Comment by GTrunSec** [comment]
looks good, thanks for your work.

**Pull request merged**
