### PR TITLE
Improve Nix (flakes) setup

### PR DESCRIPTION
**Pull request by garbas**
Depends on #194

### CODE REVIEW

**Comment by guaraqe** [comment]
I rebased the PR, the errors are a bit mysterious for me.

**Comment by guaraqe** [comment]
This broke the examples: for example when I do `nix-shell` in `examples/Haskell`, I get:

```
error: attribute 'jupyter_contrib_core' missing

       at /home/juan/tweag/jupyterWith/nix/default.nix:35:9:

           34|         python3.ipykernel
           35|         python3.jupyter_contrib_core
             |         ^
           36|         python3.jupyter_nbextensions_configurator
```

**Comment by guaraqe** [comment]
We have a segmentation fault in the CI:

```
/Users/runner/work/_temp/99d61551-9df3-4fa8-85c1-830f8737f76e.sh: line 5:  1610 Segmentation fault: 11  nix build .#jupyterEnvironment .#build .#core --accept-flake-config --show-trace
```

I am not sure how to test that locally.

**Comment by garbas** [comment]
@guaraqe I think we have some funny bug in Nix :) but I managed to trick it to pass.

**Comment by guaraqe** [comment]
I need to do the following change to make the Haskell kernel work:

```diff
-  flake = import ../../default.nix {};
+  flake = import ../../default.nix;
```

Is that expected?

The Python example is not working, I would like to refactor it. Is the example of the Haskell shell what we are expecting?

**Comment by guaraqe** [comment]
NOTICE: This PR is closed, but will be used as the basis for the next major version of JupyterWith. The new version will be developed around the `next` branch.

@garbas @k1nkreet

**Pull request closed without merging**
