### PR TITLE
Add testbook tests

### PR DESCRIPTION
**Pull request by jlesquembre**

### CODE REVIEW

**Comment by djacu** [comment]
C++, OCaml, and Ruby didn't work in my local testing so I'm not surprised to see them fail here. I only built the postgresql kernel and never verified if it actually worked.

## Ansible

I thought ansible had worked previously but it fails when I try test notebook on `main` again.

## Elm

Elm had worked for me in the past and it worked for me again when working off of `main`, but I do get this message in the terminal I hadn't seen before.

```
Hello! Elm projects always start with an elm.json file. I can create them!

Now you may be wondering, what will be in this file? How do I add Elm files to
my project? How do I see it in the browser? How will my code grow? Do I need
more directories? What about tests? Etc.

Check out <https://elm-lang.org/0.19.1/init> for all the answers!

Knowing all that, would you like me to create an elm.json file now? [Y/n]: yOkay, I created it. Now read that link!
```

## Haskell

I don't have an old notebook so I can't say for certain but I thought I had tested this kernel before.

## Javascript

It works for me on my local system. 

## Julia

It works for me on my local system. There is a little stateful setup that is required. I wonder if that is causing some issues.

**Comment by djacu** [comment]
Found this is in the elm notebook. Could be it is trying to use the c++ kernel.
```
"metadata": {
  "kernelspec": {
   "display_name": "Example C++ Kernel",
   "language": "cpp",
   "name": "example_cpp"
  },
  "language_info": {
   "file_extension": ".cpp",
   "mimetype": "text/plain",
   "name": "cpp"
  }
 },
```

**Comment by garbas** [comment]
Merge current `main` and resolved conflicts.

**Comment by jlesquembre** [comment]
IMO, we could merge this and address the failing tests in different PRs.

Some kernel tests (C++, Ocaml and Ruby) fail because the kernels are broken (at least I wasn't able to run those locally). GitHub Actions is missing an "Allow Failure" mode/configuration, see https://github.com/community/community/discussions/15452, but I marked those as `(experimental)` in the job name

**Pull request merged**
