### PR TITLE
Next feature/update documenation

### PR DESCRIPTION
**Pull request by djacu**
Updated template welcome text.
Fixed template python kernel name.
Added instructions in the template readme for extending existing kernels and creating custom kernels.

### CODE REVIEW

**Comment by GTrunSec** [comment]
Are you sure you can load the extra packages PYTHONPATH correctly?

**Comment by GTrunSec** [comment]
I tested the latest next branch and explored that python's kernel and sys.path could not load the PYTHONPATH of the extraPackages.

**Comment by djacu** [comment]
Using `extraPackages` is a goal but currently is not working. I haven't investigated why it isn't working yet. Is that where `poetry2nix` is looking for extra packages? In `PYTHONPATH`?

**Comment by djacu** [comment]
No, `import numpy` not when using the `extraPackages` on my python kernel.

**Comment by GTrunSec** [comment]
In jupytext's use case, we also neeed a PYTHONPATH that wraps to jupyterlab. If poetryPyEnv points correctly to python kernel, it should be a wrapped poetry path.

- my config
1:0:emacs -  NixOS   2022-09-07 18-24-50


- kernel sys.path check: 
- Untitled ipynb (auto-3) - JupyterLab 2022-09-07 18-23-45

- jupyter kernelspec list: 0:1:zsh -  NixOS  2# 2022-09-07 18-24-31

**Comment by GTrunSec** [comment]
- two options here: fix the current poetryEnv to be loaded correctly by the kernel. or extend PYTHONPATH to the current kernel environment.

0:1: tmux  -  NixOS   2022-09-07 20-15-09

Untitled ipynb - JupyterLab 2022-09-07 20-16-02

**Comment by garbas** [comment]
@GTrunSec thank you for the hints. I'll be working on that issue tomorrow.
@djacu awesome work on the first pass on the documentation.

**Pull request merged**
